# Generated by Django 5.0.6 on 2024-07-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_creates',
            new_name='datetime_created',
        ),
    ]
